services:
  falkdrop-db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - "5433:5432"
    volumes:
      - falkdrop_db_data:/var/lib/postgresql/
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]

  falkdrop-migrate:
    image: ghcr.io/falbru/falkdrop-server:latest
    command: ["/migrate", "up"]
    environment:
      - DATABASE_URL
    depends_on:
      falkdrop-db:
        condition: service_healthy

  falkdrop-server:
    image: ghcr.io/falbru/falkdrop-server:latest
    restart: always
    environment:
      - DATABASE_URL
      - OBJECTSTORE_PROVIDER
      - S3_BUCKET
      - AWS_DEFAULT_REGION
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - KEYCLOAK_REALM_URL
      - KEYCLOAK_CLIENT_ID
    ports:
      - "8082:8082"
    depends_on:
      falkdrop-db:
        condition: service_healthy
      falkdrop-migrate:
        condition: service_completed_successfully
      keycloak:
        condition: service_started

  falkdrop-webapp:
    image: ghcr.io/falbru/falkdrop-webapp:latest
    restart: always
    environment:
      - VITE_API_URL
    ports:
      - "5173:80"
    depends_on:
      - keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:26.6.4
    command: start
    environment:
      - KC_HOSTNAME=keycloak.falbru.dev
      - KC_HTTP_ENABLED=true
      - KC_HEALTH_ENABLED=true
      - KC_DB=postgres
      - KC_DB_URL_HOST=keycloak-db
      - KC_DB_USERNAME
      - KC_DB_PASSWORD
      - KC_PROXY=reencrypt
      - KC_PROXY_HEADERS=xforwarded
      - KC_BOOTSTRAP_ADMIN_USERNAME
      - KC_BOOTSTRAP_ADMIN_PASSWORD
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - keycloak_data:/opt/keycloak/data/
    depends_on:
      - keycloak-db

  keycloak-db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=${KC_DB_USERNAME}
      - POSTGRES_PASSWORD=${KC_DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - keycloak_db_data:/var/lib/postgresql/

volumes:
  falkdrop_db_data:
  keycloak_data:
  keycloak_db_data:
